#if NET8_0_OR_GREATER
#nullable enable
namespace ShopifySharp.Utilities;

public record AuthorizeOptions
{
    /// The authorization code generated by Shopify, which is attached to the redirect querystring when Shopify redirects the user back to your app.
    public required string Code { get; init; }
    /// The store's *.myshopify.com URL, which is attached as a parameter named <c>shop</c> on the redirect querystring.
    public required string ShopDomain { get; init; }
    /// Your app's public Client ID, also known as its public API key.
    public required string ClientId { get; init; }
    /// Your app's Client Secret, also known as its secret API key.
    public required string ClientSecret { get; init; }
}
#endif