#nullable enable
namespace ShopifySharp.Utilities;

public record AuthorizeOptions
{
    /// The authorization code generated by Shopify, which is attached to the redirect querystring when Shopify redirects the user back to your app.
    public
#if NET6_0_OR_GREATER
    required
#endif
    string Code { get; set; } = null!;

    /// The store's *.myshopify.com URL, which is attached as a parameter named <c>shop</c> on the redirect querystring.
    public
#if NET6_0_OR_GREATER
    required
#endif
    string ShopDomain { get; set; } = null!;

    /// Your app's public Client ID, also known as its public API key.
    public
#if NET6_0_OR_GREATER
    required
#endif
    string ClientId { get; set; } = null!;

    /// Your app's Client Secret, also known as its secret API key.
    public
#if NET6_0_OR_GREATER
    required
#endif
    string ClientSecret { get; set; } = null!;
}
