name: Deploy Documentation Site

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: "Build documentation site"
    environment: Documentation deployment environment
    permissions:
      contents: read

    steps:
    - name: Setup justfile
      uses: taiki-e/install-action@67729d5c413db75907f0ad1e39bb04b9c868ff60 # v2.85.7
      with:
        tool: just@1.46.0

    - name: Setup SSH
      uses: burtek/setup-ssh@cd5d34ac7bad6529ab7ad43fa846ac0aaec87d32 # v1.0.2
      with:
        alias: "shopifysharp-docs"
        user: "shopifysharp-deploy"
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST_KEY }}
        key_filename: "id_rsa"
        strict_host_key_checking: "yes"
        test_connection: "false"

    - name: Checkout branch
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ github.ref }}
        persist-credentials: false

    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66dd77 # v4.1.0
      with:
        version: 12.3.4

    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v3
      with:
        node-version: 26

    - name: Build documentation site
      run: just astro-build-docs

    - name: Create documentation site artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: docs-dist
        if-no-files-found: error
        path: |
          docs/dist/**/*

    - name: Deploy documentation site
      run: just deploy-docs
